### ISSUE TITLE
Uncaught TypeError: $.fancybox is not a function

### ISSUE THREAD

**Issue by andresen007** [ansata-biz/sir-trevor-responsive-filemanager#1]
Hey,

I got this error in line 40 in file: sir-trevor-responsive-filemanager.js 
-> Uncaught TypeError: $.fancybox is not a function

**Comment by e1himself** [comment]
Hi @andresen007!

This plugin relies on jQuery and Fancybox to show popup. 
You should include it on your page to make this functionality work.

**Comment by e1himself** [comment]
Also, as you might know, Fancybox 2 is not free, so we use old [Fancybox 1.x](http://fancybox.net/) version wich is free and fully functional. You can download it here: 
http://fancybox.googlecode.com/files/jquery.fancybox-1.3.4.zip

**Comment by andresen007** [comment]
Hey @e1himself ,

I have tried included fancybox and jQuery. I have tried two different version of jQuery: v1.9.1 and v1.11.3. I forget to post these errors with v1.11.3: 

m.event.dispatch @ jquery.min.js:4
m.event.add.r.handle @ jquery.min.js:4

I have tried to include fancybox in head-tag and after sir-trevor.js. 

And thank you for your time and answers.

**Comment by andresen007** [comment]
Hey,

I found the solution. I have to include:
code.jquery.com/jquery-1.11.3.min.js
code.jquery.com/jquery-migrate-1.2.1.min.js

**Comment by e1himself** [comment]
@andresen007 

I'm glad you figured out what was the problem!

Good luck!
